name: Feature suggestion
description: For Lab4.1.4 New Feature Template.
title: "Feature: "
labels: ["feature", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature suggestion!
  - type: dropdown
    id: version
    attributes:
      label: Type of request?
      description: Select the type of your request.
      options:
        - New Feature
        - Fix Feature
        - Improve Feature
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Windows
        - Linux
        - DOS
        - macOS
        - iOS
        - Android
  - type: textarea
    id: feature_details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what you want.
      render: shell
      value: "Feature details!"
    validations:
      required: true



